# Generated by Django 5.0.14 on 2026-07-28 15:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concept_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('mastery_score', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('next_review_due', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_nodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_nodes',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=1.0)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='knowledge_graph.knowledgenode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='knowledge_graph.knowledgenode')),
            ],
            options={
                'db_table': 'knowledge_edges',
            },
        ),
    ]
